/// <reference types="node" />

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const datasourceUrl = process.env.DIRECT_URL ?? process.env.DATABASE_URL;

if (!datasourceUrl) {
  throw new Error(
    "Missing database connection string. Set DIRECT_URL (preferred for migrations) or DATABASE_URL in server/.env."
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use direct connection for migrations/DDL when available.
    // Keep DATABASE_URL for runtime (often a pooler) in src/prisma.ts.
    url: datasourceUrl,
  },
});
